configured_endpoints: 14
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/the-violet-company%2Frocktick-caee3e5758b046f0ad7805f18fe6e3c1dcdfec313fb597afc280e7433878b27c.yml
openapi_spec_hash: ed05ce27ceec1a69b850a7097cb7bbd3
config_hash: 41bea983ba6cd6183ebd9c01fe607f62
